version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # We want to make sure the database is loaded before
  youtubeify:
    image: jbstepan/youtubeify
    container_name: youtubeify
    ports:
      - 8080:8080
      - 6969:6969
    volumes:
      - "/some/path:/downloads" # The base downloads folder
    environment:
      - BEHIND_PROXY="false"
      - MONGODB_CONNECTION="mongodb://root:example@mongodb:27017/"